### ISSUE TITLE
fatal error: libavresample/avresample.h: No such file or directory

### ISSUE THREAD

**Issue by srt** [BetterVoice/freeswitch-container#1]
When building the image I get the following error:

```
make[4]: Entering directory `/usr/src/freeswitch/src/mod/applications/mod_av'
  CC       mod_av_la-mod_av.lo
  CC       mod_av_la-avformat.lo
avformat.c:40:38: fatal error: libavresample/avresample.h: No such file or directory
 #include <libavresample/avresample.h>
                                      ^
compilation terminated.
make[4]: *** [mod_av_la-avformat.lo] Error 1
make[4]: Leaving directory `/usr/src/freeswitch/src/mod/applications/mod_av'
```

**Comment by thomasquintana** [comment]
I apologize for the slow response time during the holiday season but the image should be working fine now. We are working on getting `mod_av` to properly build and I will update this ticket as soon as that issue is resolved.

FYI, you can always find pre-built containers @ the [docker registry](https://hub.docker.com/r/bettervoice/freeswitch-container/).

**Comment by jlmendo11** [comment]
I have the same error, but I can't use dockers. Will you fix it someday?

**Comment by jlmendo11** [comment]
I could solve this by installing a lot of dependencies. Here is one list that may not be completed or optimal, but it worked for me:

1. First I installed the Cheese repository
`wget http://www.nosuchhost.net/~cheese/fedora/packages/epel-7/x86_64/cheese-release-7-1.noarch.rpm`
`rpm -Uvh cheese-release-7-1.noarch.rpm`
`rm -f cheese-release-7-1.noarch.rpm`

2. I install some libraries
`yum install -y libavformat-devel`
`yum install -y libswscale-devel`
`yum install -y ffmpeg ffmpeg-devel`
`yum install -y libtool`
`yum install -y unixODBC`
`yum install -y unixODBC-devel`

3. I follow the instruction from the official page: https://freeswitch.org/confluence/display/FREESWITCH/CentOS+7+and+RHEL+7#CentOS7andRHEL7-CentOS7andRHEL7-Stable

The first time I run my installer script I always get this error:
`checking for sqlite3 >= 3.6.20... Package sqlite3 was not found in the pkg-config search path. Perhaps you should add the directory containing `sqlite3.pc' to the PKG_CONFIG_PATH environment variable No package 'sqlite3' found`
`configure: error: Library requirements (sqlite3 >= 3.6.20) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them.`

BUT THE SECOND TIME I run it, I always get Freeswitch installed correctly! (I think something about their code is not written in the proper order)

**Comment by jlmendo11** [comment]
I could solve this by installing a lot of dependencies. Here is one list that may not be completed or optimal, but it worked for me:

1. First I installed the Cheese repository
`wget http://www.nosuchhost.net/~cheese/fedora/packages/epel-7/x86_64/cheese-release-7-1.noarch.rpm`
`rpm -Uvh cheese-release-7-1.noarch.rpm`
`rm -f cheese-release-7-1.noarch.rpm`

2. I install some libraries
`yum install -y libavformat-devel`
`yum install -y libswscale-devel`
`yum install -y ffmpeg ffmpeg-devel`
`yum install -y libtool`
`yum install -y unixODBC`
`yum install -y unixODBC-devel`

3. I follow the instruction from the official page: https://freeswitch.org/confluence/display/FREESWITCH/CentOS+7+and+RHEL+7#CentOS7andRHEL7-CentOS7andRHEL7-Stable

The first time I run my installer script I always get this error:
`checking for sqlite3 >= 3.6.20... Package sqlite3 was not found in the pkg-config search path. Perhaps you should add the directory containing 'sqlite3.pc' to the PKG_CONFIG_PATH environment variable No package 'sqlite3' found`

`configure: error: Library requirements (sqlite3 >= 3.6.20) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them.`

BUT THE SECOND TIME I run it, I always get Freeswitch installed correctly! (I think something about their code is not written in the proper order)
