### ISSUE TITLE
Cannot run/setup

### ISSUE THREAD

**Issue by jcroy** [BetterVoice/freeswitch-container#7]
I am attempting to dockerize freeswitch for work, but I am running into all sorts of roadblocks.  The first one occurs after I build the image using the dockerfile.  After I get the image I try to start it using the command that you guys listed in the description under running the container.  That pulls down more data, although this might be because I didnt change the version number so it thought I wanted an older version (I'm not sure where I went wrong on this).   

After that a container does show up when I check it with docker ps -a.  Running it does not work with the command provided, and I cannot seem to start like I usually do with containers.  

Any ideas? If someone has setup a freeswitch containerr, which I am assuming most of everyone reading this has do you might posting the exact steps you did.  Maybe I am overlooking something or missing something, its hard to say especially since docker is pretty new to me along with everything else I am doing currently.

**Comment by lylepratt** [comment]
The below should work fine:
```
# Pull the container
sudo docker pull bettervoice/freeswitch-container:1.6.16
# Run the container
sudo docker run --name freeswitch --net=host -d --privileged bettervoice/freeswitch-container:1.6.16
# Access the running container
sudo docker exec -it freeswitch bash
```

**Comment by jcroy** [comment]
Wow I've spent so much time trying to get it to work.  This makes me angry that I overlooked it.  Is the reason docker pull ... took so much less time is because it was pulling the image down as opposed to creating it from scrach? And is everything on freeswitch ready to configure/be used?  Looking at the run command I think that permissions and networking is taken care of.

**Comment by lylepratt** [comment]
Freeswitch is ready to be used, but yes there are lots of possible things to configure including ports, sip profiles, dialplans, etc. Those things are all out of the scope of this container and should be directed to the Freeswitch mailing list or hipchat.

**Comment by jcroy** [comment]
Ok cool I just wanted to check to make sure its "ready to go".  One more thing, when I built freeswitch from their bitbucket docker repo, I would launch freeswitch (or at least view the console) simply by entering freeswitch.  How would I do this in this container? Thanks for the help, I am in completely unfamiliar territory right now.

**Comment by lylepratt** [comment]
Unfortunately, I do not know what sort of service alias they used to tie the docker image to that particular command. That is not standard docker. It sounds like it would be helpful for you to read up on some Docker tutorials.

**Comment by jcroy** [comment]
Well thank you for the quick help, its the closet I have gotten to my objective so far.
